check_name = [
["chicago", "chitown", "chi-town"],
["new york", "nyc", "new york city", "manhattan", "central park"],
["casablanca"],
["tokyo"],
["st. louis", "st louis", "saint louis"],
["taipei"],
["venice"],
["bern"],
["toronto"],
["scottsdale"],
["hong kong", "hk"],
["san francisco", "sf", "san fran"],
["cork", "cobh"],
["alesund"],
["moscow", "moskva"],
["pachuca"],
["new orleans"],
["tel aviv"],
["sydney"],
["vancouver", "vancity"],
["dubai"],
["chongqing"],
["paris"],
["amalfi"],
["los angeles"],
["seattle"],
["london"],
["berlin"],
["prague"],
["budapest"],
["vienna"],
["amsterdam"],
["montreal"],
["singapore"],
["melbourne"],
["miami"],
["buenos aires"],
["cape town"],
["atlanta"],
["kyoto"],
["seoul"],
["barcelona"],
["madrid"],
["rome", "vatican"],
["naples"],
["positano"],
["milan"],
["lisbon", "lisboa"],
["stockholm"],
["copenhagen"],
["edinburgh"],
["dublin"],
["ottawa"],
["oslo"],
["st. petersburg", "st petersburg", "saint petersburg"],
["quebec", "quebec city", "québec", "québec city"],
["detroit"],
["cleveland"],
["reykjavík"],
["wrocław"],
["boston"],
["shanghai"],
["istanbul"],
["helsinki"],
["zagreb"],
["astana"],
["iquique"],
["bangkok"],
["rio de janeiro", "rio", "copacabana"],
["austin"],
["philadelphia"],
["ronda"],
["phoenix"],
["portland"],
["las vegas"],
["sao paulo"],
["lima"],
["mexico city", "cdmx"],
["havana"],
["brisbane"],
['auckland'],
["beijing"],
["wuhan"],
["shenzhen"],
["guangzhou"],
["kuala lumpur"],
["ankara"],
["jersualem"],
["alexandria"],
["marakesh", "marrakesh", "marrakech"],
["monte carlo", "monaco"],
["seville"],
["marseille"],
["cairo"],
["guadalajara"],
["san diego"],
["monterrey"],
["santiago"],
["calgary"],
["edmonton"],
["belfast"],
["birmingham"],
["columbus"],
["cincinatti"],
["pittsburgh", "pittsburg"],
["charleston"],
["augusta"],
["athens"],
["savannah"],
["st. augustine"],
["kansas city", "kc"],
["dallas"],
["houston", "h-town"],
["el paso"],
["denver"],
["salt lake city"],
["lyon"],
["brussels", "bruxelles"],
["ghent", "gent"],
["bruges", "brugges"],
["antwerp"],
["osaka"],
["warsaw"],
["kingston"],
["minsk"],
["sevastapol", "sevastapool"],
["kiev", "kyev", "kyiv"],
["shimla"],
["agra"],
["jaipur"],
["islamabad"],
["mecca"],
["damascus"],
["mumbai", "bombay"],
["santorini"],
["cinque terre"],
["genoa"],
["zurich"],
["geneva"],
["lagos"],
["johannesburg"],
["porto"],
["portofino"],
["dresden"],
["assisi"],
["hamburg"],
["valetta"],
["aachen"],
["annecy"],
["lucerne"],
["la plata"],
["banff"],
["obanazawa"],
["vladikavkaz"],
["cesky krumlov"],
["salzburg"],
["canberra"],
["sirmione"],
["lucca"],
["como"],
["bamburg"],
["macau"],
["madison"],
["haifa"],
["chengdu"],
["baku"],
["tbilisi"],
["guanajuato"],
["lodz"],
["bergen"],
["antofagasta"],
["colmar"],
["anchorage"],
["newcastle"],
["rotterdam"],
["tehran", "teheran"],
["vladivostok"],
["gangi"],
["polignano"],
["norilsk"],
["granada"],
["puerto varas"],
["baghdad"],
["valenica"],
["manchester"],
["leeds"],
["washington", "dc", "washington dc", "washington d.c."]
]
